# Generated by Django 5.2.13 on 2026-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]

