"""
Django settings for Job_Post project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# WHY THIS FILE EXISTS:
#   This is the brain of your Django project. Every
#   setting that controls how your app behaves lives here.
#   In real companies, this file often has dev/staging/prod
#   versions (settings_dev.py, settings_prod.py).

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m%28ca1u13+_doy!vgak)*)2ul2l-(7+q8l*tdk&xzc8-s*0g#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

#WHY: Django needs to know which apps exist in your project.
#      Third-party packages also register here so Django loads their models,
#      admin classes, and template tags.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ## Third-Party Packages
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    ## Our Custom Apps
    'accounts',  # Handles: register, login, logout, user profiles
    'jobs',    # Handles: job listings, applications, filtering
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Job_Post.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # WHY 'DIRS': Tell Django to look in the root /templates folder.
        # This is where base.html lives (shared across all apps).
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,   # Also look in each app's own /templates folder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Job_Post.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # In production you'd use PostgreSQL:
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'hirehub_db',
        # 'USER': 'postgres', 'PASSWORD': '...', 'HOST': 'localhost'
    }
}

# ─── CUSTOM USER MODEL ────────────────────────────────────────────────────────
# WHY: We created a custom User model in accounts/models.py with extra fields
#      like 'role' (employer vs candidate). We MUST tell Django to use it.
#      This must be set BEFORE running your first migration.
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/jobs/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
 
# ─── DJANGO REST FRAMEWORK (DRF) ──────────────────────────────────────────────
# WHY: This configures how ALL your APIs behave by default.
#      You can override these settings on individual views too.
REST_FRAMEWORK = {
 
    # AUTHENTICATION: "Who are you?"
    # ─────────────────────────────
    # JWTAuthentication  → Used by mobile apps / Postman (send token in header)
    # SessionAuthentication → Used by browsers (cookie-based, for browsable API)
    # When a request comes in, DRF tries each class in order until one works.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    # PERMISSION: "What are you allowed to do?"
    # ─────────────────────────────────────────
    # IsAuthenticated → Must be logged in to use ANY API endpoint.
    # Override per-view for public endpoints (e.g., job listings).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # FILTER BACKENDS: Enable filtering, search, ordering globally
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # ?status=open
        'rest_framework.filters.SearchFilter',                # ?search=python
        'rest_framework.filters.OrderingFilter',              # ?ordering=-created_at
    ],

    # PAGINATION: Return data in pages, not all at once
    # WHY: If you have 10,000 jobs, you don't return all in one response.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}
 
# ─── JWT TOKEN SETTINGS ───────────────────────────────────────────────────────
# WHY THIS MATTERS IN INTERVIEWS:
#   Companies always ask: "How do you handle token expiry?"
#   Answer: Access token is short-lived (15 min). When it expires,
#   the client uses the refresh token (7 days) to get a new access token.
#   This way, even if access token is stolen, it expires quickly.
SIMPLE_JWT = {
    # Short-lived — expires in 15 minutes
    # Client sends this in every API request header:
    # Authorization: Bearer <access_token>
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
 
    # Long-lived — expires in 7 days
    # Client uses this ONLY to get a new access token when it expires
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
 
    # If True: every time refresh is used, a brand new refresh token is issued
    # This is more secure (old refresh token becomes invalid)
    'ROTATE_REFRESH_TOKENS': True,
 
    # Blacklist old refresh tokens after rotation (requires extra app — optional)
    'BLACKLIST_AFTER_ROTATION': False,
 
    'ALGORITHM': 'HS256',          # Signing algorithm
    'AUTH_HEADER_TYPES': ('Bearer',),  # Token type in header: "Bearer <token>"
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
 
# ─── FILE UPLOADS ─────────────────────────────────────────────────────────────
# WHY: Candidates upload their resume (PDF). Django stores it in /media/ folder.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


