# Generated by Django 5.2.13 on 2026-04-15 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('weather_type', models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Snowy', 'Snowy')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='weather_images/')),
            ],
        ),
    ]
